### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by kingbuzzman** [Instagram/LibCST#448] opened 2021-01-19 16:19 UTC
Python 3.6.8
Linux 28002f3c2045 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux (docker)
libcst==0.3.16

Ran across this issue, any recommendations would be helpful.

```
cat << 'EOF' > /tmp/issue.py
# -*- coding: utf-8 -*-

var1 = b'\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00;\x00\x03\x00\xfe\xff\t\x00\x06\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x01\x00\x00\x00' \
   b'\x0b\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x10\x00\x00\x02\x00\x00\x00' \
   b'\x01\x00\x00\x00' \
   b'\xfe\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfd\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff\x04\x00\x00\x00' \
   b'\x05\x00\x00\x00' \
   b'\x06\x00\x00\x00' \
   b'\x07\x00\x00\x00' \
   b'\x08\x00\x00\x00' \
   b'\t\x00\x00\x00' \
   b'\n\x00\x00\x00' \
   b'\xfe\xff\xff\xff\x0c\x00\x00\x00' \
   b'\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffR\x00o\x00o\x00t\x00 \x00E\x00n\x00t\x00r\x00y\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x16\x00\x05\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xfe\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xfe\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xfe\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xfe\xff\xff\xff\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x01\x00\x00\x00' \
   b'\x02\x00\x00\x00' \
   b'\x03\x00\x00\x00' \
   b'\x04\x00\x00\x00' \
   b'\x05\x00\x00\x00' \
   b'\x06\x00\x00\x00' \
   b'\x07\x00\x00\x00' \
   b'\x08\x00\x00\x00' \
   b'\t\x00\x00\x00' \
   b'\n\x00\x00\x00' \
   b'\x0b\x00\x00\x00' \
   b'\x0c\x00\x00\x00' \
   b'\r\x00\x00\x00' \
   b'\x0e\x00\x00\x00' \
   b'\x0f\x00\x00\x00' \
   b'\x10\x00\x00\x00' \
   b'\x11\x00\x00\x00' \
   b'\x12\x00\x00\x00' \
   b'\x13\x00\x00\x00' \
   b'\x14\x00\x00\x00' \
   b'\x15\x00\x00\x00' \
   b'\x16\x00\x00\x00' \
   b'\x17\x00\x00\x00' \
   b'\x18\x00\x00\x00' \
   b'\x19\x00\x00\x00' \
   b'\x1a\x00\x00\x00' \
   b'\x1b\x00\x00\x00' \
   b'\x1c\x00\x00\x00' \
   b'\x1d\x00\x00\x00' \
   b'\x1e\x00\x00\x00' \
   b'\x1f\x00\x00\x00 \x00\x00\x00!\x00\x00\x00"\x00\x00\x00#\x00\x00\x00$\x00\x00\x00%\x00\x00\x00&\x00\x00\x00' \
   b'\'\x00\x00\x00(\x00\x00\x00)\x00\x00\x00*\x00\x00\x00+\x00\x00\x00,\x00\x00\x00-\x00\x00\x00.\x00\x00\x00/\x00\x00\x000\x00\x00\x001\x00\x00\x002\x00\x00\x003\x00\x00\x00' \
   b'\xfe\xff\xff\xff5\x00\x00\x00' \
   b'\xfe\xff\xff\xff\xfe\xff\xff\xff8\x00\x00\x009\x00\x00\x00:\x00\x00\x00' \
   b'\xfe\xff\xff\xff<\x00\x00\x00' \
   b'\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' \
   b'\xff\t\x08\x10\x00\x00\x06\x05\x00\xbb\r\xcc\x07\x00\x00\x00' \
   b'\x00\x06\x00\x00\x00' \
   b'\xe1\x00\x02\x00\xb0\x04\xc1\x00\x02\x00\x00\x00' \
   b'\xe2\x00\x00\x00' \
   b'\\\x00p\x00\x04\x00\x00Calc                                                                                                         B\x00\x02\x00\xb0\x04a\x01\x02\x00\x00\x00' \
   b'\xc0\x01\x00\x00=\x01\x06\x00\x01\x00\x02\x00\x03\x00\x9c\x00\x02\x00\x0e\x00\xaf\x01\x02\x00\x00\x00' \
   b'\xbc\x01\x02\x00\x00\x00=\x00\x12\x00\x00\x00' \
   b'\x00\x00\x00@\x00 8\x00\x00\x00' \
   b'\x00\x00\x01\x00\xc2\x00@\x00\x02\x00\x00\x00' \
   b'\x8d\x00\x02\x00\x00\x00"\x00\x02\x00\x00\x00' \
   b'\x0e\x00\x02\x00\x01\x00\xb7\x01\x02\x00\x00\x00' \
   b'\xda\x00\x02\x00\x00\x001\x00\x1a\x00\xc8\x00\x00\x00' \
   b'\xff\x7f\x90\x01\x00\x00\x00' \
   b'\x02\x00\x00\x05\x01A\x00r\x00i\x00a\x00l\x001\x00\x1a\x00\xc8\x00\x00\x00' \
   b'\xff\x7f\x90\x01\x00\x00\x00' \
   b'\x00\x00\x00\x05\x01A\x00r\x00i\x00a\x00l\x001\x00\x1a\x00\xc8\x00\x00\x00' \
   b'\xff\x7f\x90\x01\x00\x00\x00' \
   b'\x00\x00\x00\x05\x01A\x00r\x00i\x00a\x00l\x001\x00\x1a\x00\xc8\x00\x00\x00' \
   b'\xff\x7f\x90\x01\x00\x00\x00' \
   b'\x00\x00\x00\x05\x01A\x00r\x00i\x00a\x00l\x001\x00\x1e\x00\xdc\x00\x00\x00' \
   b'\x08\x00\xbc\x02\x00\x00\x00' \
   b'\x02\x01\x00\x07\x01C\x00a\x00l\x00i\x00b\x00r\x00i\x001\x00\x1e\x00\xdc\x00\x00\x00' \
   b'\x08\x00\x90\x01\x00\x00\x00' \
   b'\x02\x01\x00\x07\x01C\x00a\x00l\x00i\x00b\x00r\x00i\x00\x1e\x04\x0c\x00\xa4\x00\x07\x00\x00GENERAL\xe0\x00\x14\x00\x00\x00' \
   b'\xa4\x00\xf5\xff \x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\xc0 \xe0\x00\x14\x00\x01\x00\x00\x00' \
   b'\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x01\x00\x00\x00' \
   b'\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x02\x00\x00\x00' \
   b'\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x02\x00\x00\x00' \
   b'\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\x00\x00\xf5\xff \x00\x00\xf4\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x00\x00' \
   b'\xa4\x00\x01\x00 \x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\xc0 \xe0\x00\x14\x00\x01\x00+\x00\xf5\xff \x00\x00\xf0\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x01\x00)\x00\xf5\xff \x00\x00\xf0\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x01\x00,\x00\xf5\xff \x00\x00\xf0\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x01\x00*\x00\xf5\xff \x00\x00\xf0\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x01\x00\t\x00\xf5\xff \x00\x00\xf0\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \xe0\x00\x14\x00\x06\x00\xa4\x00\xf5\xff \x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\xc0 \xe0\x00\x14\x00\x05\x00\xa4\x00Q\x01 \x00\x00\x08\x00\x00\x00' \
   b'\x00\x00\x00\x00' \
   b'\x00\xc0 \x93\x02\x04\x00\x00\x80\x00\xff\x93\x02\x04\x00\x10\x80\x03\xff\x93\x02\x04\x00\x11\x80\x06\xff\x93\x02\x04\x00\x12\x80\x04\xff\x93\x02\x04\x00\x13\x80\x07\xff\x93\x02\x04\x00\x14\x80\x05\xff\x93\x02\x1a\x00\x15\x00\x15\x00\x00Excel Built-in Normal`\x01\x02\x00\x01\x00\x85\x00\x0e\x00\xbc\x05\x00\x00\x00' \
   b'\x00\x06\x00Sheet1\x85\x00\x0e\x00#\t\x00\x00\x00' \
   b'\x00\x06\x00Sheet2\x85\x00\x0e\x00\x02\x0b\x00\x00\x00' \
   b'\x00\x06\x00Sheet3\x8c\x00\x04\x00\x01\x00\x01\x00\xc1\x01\x08\x00\xc1\x01\x00\x00T\x8d\x01\x00\xeb\x00j\x00\x0f\x00\x00\xf0b\x00\x00\x00' \
   b'\x00\x00\x06\xf0(\x00\x00\x00' \
   b'\x00\x0c\x00\x00\x04\x00\x00\x00' \
   b'\x03\x00\x00\x00' \
   b'\x03\x00\x00\x00' \
   b'\x01\x00\x00\x00' \
   b'\x01\x00\x00\x00' \
   b'\x02\x00\x00\x00' \
   b'\x01\x00\x00\x00'
EOF

python -c "$(cat << 'EOF' -
import libcst as cst

class BugTransformer(cst.CSTTransformer):
    pass

with open('/tmp/issue.py') as r_f:
    source_tree = cst.parse_module(r_f.read())

transformer = BugTransformer()
modified_tree = source_tree.visit(transformer)

EOF
)"
```

Stack:

```
Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/module.py", line 91, in visit
    result = super(Module, self).visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/module.py", line 75, in _visit_and_replace_children
    body=visit_body_sequence(self, "body", self.body, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 200, in visit_body_sequence
    return tuple(visit_body_iterable(parent, fieldname, children, visitor))
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 172, in visit_body_iterable
    new_child = child.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/statement.py", line 424, in _visit_and_replace_children
    body=visit_sequence(self, "body", self.body, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 156, in visit_sequence
    return tuple(visit_iterable(parent, fieldname, children, visitor))
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 140, in visit_iterable
    new_child = child.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/statement.py", line 1303, in _visit_and_replace_children
    value=visit_required(self, "value", self.value, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 1012, in _visit_and_replace_children
    right=visit_required(self, "right", self.right, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 1012, in _visit_and_replace_children
    right=visit_required(self, "right", self.right, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 1012, in _visit_and_replace_children
    right=visit_required(self, "right", self.right, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 1012, in _visit_and_replace_children
    right=visit_required(self, "right", self.right, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
 
 .... bellow repeats 400+ times....
 
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 1012, in _visit_and_replace_children
    right=visit_required(self, "right", self.right, visitor),
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/internal.py", line 81, in visit_required
    result = node.visit(visitor)
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 225, in visit
    _CSTNodeSelfT, self._visit_and_replace_children(visitor)
    
 ..... ^^^^^^^ above repeats ^^^^^^ ........
 
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 1013, in _visit_and_replace_children
    rpar=visit_sequence(self, "rpar", self.rpar, visitor),
  File "<string>", line 7, in __init__
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/base.py", line 115, in __post_init__
    self._validate()
  File "/usr/local/lib/python3.6/site-packages/libcst/_nodes/expression.py", line 994, in _validate
    if isinstance(right, ConcatenatedString):
  File "/usr/local/lib/python3.6/abc.py", line 190, in __instancecheck__
    subclass in cls._abc_negative_cache):
  File "/usr/local/lib/python3.6/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by thatch** [comment] 2021-01-19 17:08
This is a dupe of #409 -- you can probably fix your script with adding

```py
import sys
sys.setrecursionlimit(4000)  # 10x the default
```

before the call to `visit`

**Closed by thatch** 2021-01-19 17:08 UTC

**Comment by kingbuzzman** [comment] 2021-01-19 17:10
i'll try thank, thank you!
