### ISSUE TITLE
White space around positional-only parameters

### ISSUE THREAD

**Issue by MrVPlusOne** [Instagram/LibCST#685] opened 2022-05-11 15:48 UTC
Hi,

It looks like LibCST current does not preserve the whitespaces when parsing code with position-only arguments. For example, if we call libcst to parse the following code

```python
def __init__(
    self, check_interval: int, folder: Path, /
) -> None:
    super().__init__(check_interval, "AutoLocker")

    self._autolocked: Dict[Path, int] = {}
    self._lockers: Dict[Path, "DirectEdit"] = {}
    self._to_lock: Items = []
```

and then run code generation, we would get back
```python
def __init__(
    self, check_interval: int, folder: Path, /) -> None:
    super().__init__(check_interval, "AutoLocker")

    self._autolocked: Dict[Path, int] = {}
    self._lockers: Dict[Path, "DirectEdit"] = {}
    self._to_lock: Items = []
```

This can break applications that rely on libsct preserving the original source code (which I ran into). I'm using Python 3.10 with `LIBCST_PARSER_TYPE=native`. Thanks.

**Comment by zsol** [comment] 2022-05-11 18:09
duplicate of #679.

**Closed by zsol** 2022-05-11 18:09 UTC
